x1=(0,1,2,3,4,5,5,6)
n=x1.count(2)
print("the count of 3 is:",n)
n=sum(x1)
print("the sum of n is:",n)
n=min(x1)
print("the min value of n is:",n)
n=max(x1)
print("the max value of n is:",n)
n=len(x1)
print("the length of x1 is:",n)
n=sorted(x1)
print("the sorted tuple is:",n) 